[scavenger_servers]
# Target VM host IP / domain for production deployment
# production.adventuretogether.org ansible_user=deploy ansible_ssh_private_key_file=~/.ssh/id_rsa
localhost ansible_connection=local

[scavenger_servers:vars]
ansible_python_interpreter=/usr/bin/python3
project_root=/opt/adventuretogether
app_domain=adventuretogether.org
postgres_db=adventure_together
postgres_user=adventure_user
