# Generated by Django 5.1.15 on 2026-10-05 05:04

import apps.teams.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team name chosen by participants.', max_length=255)),
                ('join_code', models.CharField(db_index=True, default=apps.teams.models.generate_join_code, help_text='Unique code used by teammates to join this group.', max_length=32, unique=True)),
                ('score', models.IntegerField(default=0, help_text='Aggregate points earned by verified quest submissions.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the team was created.')),
                ('event', models.ForeignKey(help_text='The event this team is competing in.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event')),
            ],
            options={
                'verbose_name': 'Scavenger Hunt Team',
                'verbose_name_plural': 'Scavenger Hunt Teams',
                'ordering': ['-score', 'name'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, help_text='Unique device identifier or username for the participant.', max_length=255)),
                ('display_name', models.CharField(default='Anonymous Mapper', help_text='Participant display name visible to teammates.', max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the member joined the team.')),
                ('team', models.ForeignKey(help_text='The team the user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('team', 'user_identifier')},
            },
        ),
    ]
