# Generated by Django 5.1.15 on 2026-10-05 05:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Human-readable title of the scavenger hunt event.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the event.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed overview and rules for participants.')),
                ('hashtag', models.CharField(db_index=True, help_text='Designated event hashtag (without leading #) to identify edits across OSM and Wikimedia.', max_length=100)),
                ('bounding_polygon', django.contrib.gis.db.models.fields.PolygonField(help_text='Geographic perimeter defining the hunt boundary (EPSG:4326 WGS 84).', srid=4326)),
                ('start_time', models.DateTimeField(help_text='Timestamp when the hunt begins.')),
                ('end_time', models.DateTimeField(help_text='Timestamp when the hunt concludes.')),
                ('is_active', models.BooleanField(default=True, help_text='Flag indicating whether the event is actively accepting location pings and submissions.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the event was created.')),
            ],
            options={
                'verbose_name': 'Scavenger Hunt Event',
                'verbose_name_plural': 'Scavenger Hunt Events',
                'ordering': ['-start_time', 'title'],
            },
        ),
    ]
