# Generated by Django 5.1.15 on 2026-10-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('quests', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('osm', 'OpenStreetMap'), ('commons', 'Wikimedia Commons'), ('wikidata', 'Wikidata')], help_text='Source platform of the contribution.', max_length=16)),
                ('external_id', models.CharField(db_index=True, help_text='Changeset ID, Page ID, or Revision ID on the target platform.', max_length=255)),
                ('author_username', models.CharField(db_index=True, help_text='Username of the contributor on the external platform.', max_length=255)),
                ('external_url', models.URLField(help_text='Direct link to the external changeset, photo, or item.')),
                ('diff_payload', models.JSONField(blank=True, default=dict, help_text='Structured diff showing added/modified tags, images, or statements.')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Whether a host has reviewed and verified this submission.')),
                ('verified_by_username', models.CharField(blank=True, help_text='Host username who confirmed verification.', max_length=255, null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when verification was granted.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the submission was harvested.')),
                ('event', models.ForeignKey(help_text='The event this submission belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='events.event')),
                ('quest', models.ForeignKey(blank=True, help_text='Matched quest (if criteria tags match).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='quests.quest')),
                ('team', models.ForeignKey(blank=True, help_text='Team credited with the submission (if author is a member).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='teams.team')),
            ],
            options={
                'verbose_name': 'Open Data Submission',
                'verbose_name_plural': 'Open Data Submissions',
                'ordering': ['-created_at'],
                'unique_together': {('platform', 'external_id')},
            },
        ),
    ]
