# Generated by Django 5.1.15 on 2026-10-05 05:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title of the quest challenge.', max_length=255)),
                ('description', models.TextField(help_text='Instructions for field participants.')),
                ('target_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Specific point, polygon zone, or geometry for the quest (optional, defaults to entire event perimeter).', null=True, srid=4326)),
                ('criteria_type', models.CharField(choices=[('osm_tags', 'OpenStreetMap Tag Rule'), ('wikimedia_commons', 'Wikimedia Commons Photo'), ('wikidata_entry', 'Wikidata Item Edit')], default='osm_tags', help_text='Platform and verification type for this quest.', max_length=32)),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='JSON criteria: e.g. {"required_tags": {"amenity": "restaurant", "opening_hours": "*"}, "target_count": 5}')),
                ('points_reward', models.IntegerField(default=10, help_text='Score awarded to a team upon verified completion.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this quest is active for completion.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the quest was created.')),
                ('event', models.ForeignKey(help_text='The event this quest belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='events.event')),
            ],
            options={
                'verbose_name': 'Scavenger Hunt Quest',
                'verbose_name_plural': 'Scavenger Hunt Quests',
                'ordering': ['title'],
            },
        ),
    ]
