# Generated by Django 5.1.15 on 2026-10-05 05:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, help_text='Unique device identifier or username for the participant.', max_length=255)),
                ('display_name', models.CharField(default='Anonymous Mapper', help_text='Participant display name visible on the map.', max_length=255)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(help_text='WGS 84 GPS coordinates (longitude, latitude).', srid=4326)),
                ('visibility', models.CharField(choices=[('nobody', 'Nobody'), ('team', 'Team Only'), ('quest', 'Whole Quest')], default='team', help_text='Privacy visibility scope selected by the user.', max_length=16)),
                ('is_foreground', models.BooleanField(default=True, help_text='True if the browser tab/app was active in the foreground at capture time.')),
                ('recorded_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp of the most recent coordinate update.')),
                ('event', models.ForeignKey(help_text='The active event.', on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='events.event')),
                ('team', models.ForeignKey(blank=True, help_text="The participant's team (if joined).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='teams.team')),
            ],
            options={
                'verbose_name': 'Location Ping',
                'verbose_name_plural': 'Location Pings',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
